### ISSUE TITLE
support for the new gmail UI

### ISSUE THREAD

**Issue by M0UL** [TheGoddessInari/rambox#49] opened 2018-09-03 16:57 UTC
currently notification don't work in rambox for the new gmail layout.

**Comment by TheGoddessInari** [comment] 2018-09-06 03:55
This supports the new gmail UI, are you sure that desktop notifications have been turned on?
It looks like passive listeners might interfere with the settings panel loading, for some reason. I'll see what can be done about that.

**Comment by M0UL** [comment] 2018-09-06 11:00
maybe also allow for using delegated gmail accounts to be viewed inside rambox?
url: https://mail.google.com/mail/b/{acount id}/u/0/

**Comment by NikolaZornic** [comment] 2018-09-17 09:11
Just tested, notifications are working.
Only when I click the notification:
- mail is opened in browser
- new blank Rambox window is created (named Gmail)
- Rambox main window is restored and resized (originally it was maximized)

Also, nothing from Settings menu in Gmail is working.

**Comment by TheGoddessInari** [comment] 2018-10-07 15:45
Please test again with the latest master version.

I'm seeing Settings working, can't really test the notification toasts on Ubuntu for some reason (looking into that).

**Comment by NikolaZornic** [comment] 2018-10-07 20:07
I tried with [0.5.18](https://ci.appveyor.com/api/projects/TheGoddessInari/rambox/artifacts/dist/Rambox-OS%20Setup%200.5.18.exe?job=Image%3A%20Visual%20Studio%202017&branch=master) for Windows and can't open settings. Opened console, but can't find any error on clicking settings button.

**Comment by ontherunvaro** [comment] 2018-12-04 11:31
Can reproduce the last report from @NikolaZornic, it is not possible to open the Settings dialog (or any other dialog) to activate the notifications.

**Comment by ontherunvaro** [comment] 2018-12-05 08:44
Just did a bit of testing: it won't work for me when first opening the app, but when reloading the service it starts working. This is consistent with behavior I've observed in other Google apps (Calendar shows an empty calendar until reload, and Hangouts Chat sometimes doesn't load properly on the first time). Maybe this is related to #61?

**Comment by TheGoddessInari** [comment] 2018-12-05 08:53
Oh, right, this is related to a previous comment I made about the passive listeners possibly interfering with the load screen. I was going to add it to the blacklist, but forgot.

This is strange that it's not actively causing the same problems for me, though. You're using Linux? I'll test there the next time I boot over.

**Comment by NikolaZornic** [comment] 2018-12-05 09:07
Windows 10 here, not working even after clearing site data and reloading service.
Is there any kind of log I can provide for you to troubleshoot the issue?

**Comment by NikolaZornic** [comment] 2018-12-05 12:40
OK, my bad here. I didn't use the current `master` version.
After updating, I am able to open Gmail settings.

P.S. Just a suggestion, add some kind of label to [the latest build](https://github.com/TheGoddessInari/rambox#latest-unstable-build-artifacts-are-available-in-windows-----win64-mac-dmg-and-linux-----appimage64-----rpm64-----deb64-----tarball64-packaging-flavors), so we can know if we are up to date.

**Comment by TheGoddessInari** [comment] 2018-12-05 23:44
I just added git hash/date information to builds in af081b791d57a58ba226c6ceb6d4c8dc77938259.

If you see a new commit to master, a package will be built for it as soon as it can (takes up to around 15 minutes sometimes).

**Comment by TheGoddessInari** [comment] 2019-01-23 20:11
This should be fixed for about a month and a half now.

**Closed by TheGoddessInari** 2019-01-23 20:11 UTC
