### ISSUE TITLE
Disabling eval breaks Outlook 365

### ISSUE THREAD

**Issue by JakobStruye** [TheGoddessInari/rambox#79] opened 2019-01-22 09:24 UTC
Outlook 365 becomes unusable with eval disabled.
I have no PHP knowledge so I can't really look into it any further, but I did trace the issue back to the eval disabling commit.

### Steps to reproduce

1. Add Exchange 365 service
2. Log in
3. Try to open any email
4. (Reload service or restart Rambox)

### Expected behavior

See email / have working service

### Actual behavior

Opening an email gets stuck on "Loading...". Afterwards, it's impossible to login after reloading the service or restarting the app. It runs into this error: https://cdn1.imggmi.com/uploads/2019/1/22/d6e0457eebfe0ad5e660258fb62c335a-full.png

### ENVIRONMENT

> Rambox-OS: v0.5.18 commit f46631a and later

> OS: Linux (Manjaro)

> Arch: x64

> BuildVersion:

> Does this happen upstream: yes, no, unknown, or N/A
No, it's eval().

**Comment by TheGoddessInari** [comment] 2019-01-22 20:32
Thanks for this report. Unfortunately more sites than I anticipated used this blindly (not checking for exceptions/errors), even though it's use on the open web is extremely discouraged and insecure.

Try the testing build once it's uploaded, pleased. I'll likely be pushing it to master later in the afternoon since nobody's reported any problems with `testing` over the last 11 days.

**Comment by JakobStruye** [comment] 2019-01-23 09:12
No more issues on the current master head.

What do you think about the eval checkbox as proposed in #73 by the way? Would it be "more" secure to have eval enabled only for select services that rely on it instead of having it enabled globally?

**Comment by TheGoddessInari** [comment] 2019-01-23 16:34
I'll consider it. The problem is that failures tend to be silent, despite throwing an exception. The sites ignore it, or swallow the exception so it doesn't even show up on the console, and for sites that don't use eval to begin with, it's not really doing anything anyway, I think.

Perhaps the better option at the present time is to log uses of eval to the console, so anyone working on stuff can poke, prod, and constructively pester the affected products (such as FB Messenger and Outlook 365) until such problematic issues can be fixed on their end.

**Closed by TheGoddessInari** 2019-01-23 16:34 UTC
